/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceNewRouteImport } from './routes/workspace.new'
import { Route as WorkspaceSessionIdRouteImport } from './routes/workspace.$sessionId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppDashboardIndexRouteImport } from './routes/_app.dashboard.index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'
import { Route as ApiLiveTokenRouteImport } from './routes/api.live.token'
import { Route as ApiLiveSuggestRouteImport } from './routes/api.live.suggest'
import { Route as ApiLiveSessionRouteImport } from './routes/api.live.session'
import { Route as ApiCryptomusWebhookRouteImport } from './routes/api.cryptomus.webhook'
import { Route as AppDashboardTeamRouteImport } from './routes/_app.dashboard.team'
import { Route as AppDashboardSupportRouteImport } from './routes/_app.dashboard.support'
import { Route as AppDashboardSettingsRouteImport } from './routes/_app.dashboard.settings'
import { Route as AppDashboardSessionsRouteImport } from './routes/_app.dashboard.sessions'
import { Route as AppDashboardResumeRouteImport } from './routes/_app.dashboard.resume'
import { Route as AppDashboardOrganizationRouteImport } from './routes/_app.dashboard.organization'
import { Route as AppDashboardMockRouteImport } from './routes/_app.dashboard.mock'
import { Route as AppDashboardLiveRouteImport } from './routes/_app.dashboard.live'
import { Route as AppDashboardJobDescriptionsRouteImport } from './routes/_app.dashboard.job-descriptions'
import { Route as AppDashboardInterviewPrepRouteImport } from './routes/_app.dashboard.interview-prep'
import { Route as AppDashboardCreditsRouteImport } from './routes/_app.dashboard.credits'
import { Route as AppDashboardBillingRouteImport } from './routes/_app.dashboard.billing'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceNewRoute = WorkspaceNewRouteImport.update({
  id: '/workspace/new',
  path: '/workspace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSessionIdRoute = WorkspaceSessionIdRouteImport.update({
  id: '/workspace/$sessionId',
  path: '/workspace/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveTokenRoute = ApiLiveTokenRouteImport.update({
  id: '/api/live/token',
  path: '/api/live/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSuggestRoute = ApiLiveSuggestRouteImport.update({
  id: '/api/live/suggest',
  path: '/api/live/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveSessionRoute = ApiLiveSessionRouteImport.update({
  id: '/api/live/session',
  path: '/api/live/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCryptomusWebhookRoute = ApiCryptomusWebhookRouteImport.update({
  id: '/api/cryptomus/webhook',
  path: '/api/cryptomus/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardTeamRoute = AppDashboardTeamRouteImport.update({
  id: '/dashboard/team',
  path: '/dashboard/team',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardSupportRoute = AppDashboardSupportRouteImport.update({
  id: '/dashboard/support',
  path: '/dashboard/support',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardSessionsRoute = AppDashboardSessionsRouteImport.update({
  id: '/dashboard/sessions',
  path: '/dashboard/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardResumeRoute = AppDashboardResumeRouteImport.update({
  id: '/dashboard/resume',
  path: '/dashboard/resume',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardOrganizationRoute =
  AppDashboardOrganizationRouteImport.update({
    id: '/dashboard/organization',
    path: '/dashboard/organization',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardMockRoute = AppDashboardMockRouteImport.update({
  id: '/dashboard/mock',
  path: '/dashboard/mock',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardLiveRoute = AppDashboardLiveRouteImport.update({
  id: '/dashboard/live',
  path: '/dashboard/live',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardJobDescriptionsRoute =
  AppDashboardJobDescriptionsRouteImport.update({
    id: '/dashboard/job-descriptions',
    path: '/dashboard/job-descriptions',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardInterviewPrepRoute =
  AppDashboardInterviewPrepRouteImport.update({
    id: '/dashboard/interview-prep',
    path: '/dashboard/interview-prep',
    getParentRoute: () => AppRoute,
  } as any)
const AppDashboardCreditsRoute = AppDashboardCreditsRouteImport.update({
  id: '/dashboard/credits',
  path: '/dashboard/credits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardBillingRoute = AppDashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/workspace/$sessionId': typeof WorkspaceSessionIdRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/dashboard/billing': typeof AppDashboardBillingRoute
  '/dashboard/credits': typeof AppDashboardCreditsRoute
  '/dashboard/interview-prep': typeof AppDashboardInterviewPrepRoute
  '/dashboard/job-descriptions': typeof AppDashboardJobDescriptionsRoute
  '/dashboard/live': typeof AppDashboardLiveRoute
  '/dashboard/mock': typeof AppDashboardMockRoute
  '/dashboard/organization': typeof AppDashboardOrganizationRoute
  '/dashboard/resume': typeof AppDashboardResumeRoute
  '/dashboard/sessions': typeof AppDashboardSessionsRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/support': typeof AppDashboardSupportRoute
  '/dashboard/team': typeof AppDashboardTeamRoute
  '/api/cryptomus/webhook': typeof ApiCryptomusWebhookRoute
  '/api/live/session': typeof ApiLiveSessionRoute
  '/api/live/suggest': typeof ApiLiveSuggestRoute
  '/api/live/token': typeof ApiLiveTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/workspace/$sessionId': typeof WorkspaceSessionIdRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/dashboard/billing': typeof AppDashboardBillingRoute
  '/dashboard/credits': typeof AppDashboardCreditsRoute
  '/dashboard/interview-prep': typeof AppDashboardInterviewPrepRoute
  '/dashboard/job-descriptions': typeof AppDashboardJobDescriptionsRoute
  '/dashboard/live': typeof AppDashboardLiveRoute
  '/dashboard/mock': typeof AppDashboardMockRoute
  '/dashboard/organization': typeof AppDashboardOrganizationRoute
  '/dashboard/resume': typeof AppDashboardResumeRoute
  '/dashboard/sessions': typeof AppDashboardSessionsRoute
  '/dashboard/settings': typeof AppDashboardSettingsRoute
  '/dashboard/support': typeof AppDashboardSupportRoute
  '/dashboard/team': typeof AppDashboardTeamRoute
  '/api/cryptomus/webhook': typeof ApiCryptomusWebhookRoute
  '/api/live/session': typeof ApiLiveSessionRoute
  '/api/live/suggest': typeof ApiLiveSuggestRoute
  '/api/live/token': typeof ApiLiveTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/workspace/$sessionId': typeof WorkspaceSessionIdRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/_app/dashboard/billing': typeof AppDashboardBillingRoute
  '/_app/dashboard/credits': typeof AppDashboardCreditsRoute
  '/_app/dashboard/interview-prep': typeof AppDashboardInterviewPrepRoute
  '/_app/dashboard/job-descriptions': typeof AppDashboardJobDescriptionsRoute
  '/_app/dashboard/live': typeof AppDashboardLiveRoute
  '/_app/dashboard/mock': typeof AppDashboardMockRoute
  '/_app/dashboard/organization': typeof AppDashboardOrganizationRoute
  '/_app/dashboard/resume': typeof AppDashboardResumeRoute
  '/_app/dashboard/sessions': typeof AppDashboardSessionsRoute
  '/_app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/_app/dashboard/support': typeof AppDashboardSupportRoute
  '/_app/dashboard/team': typeof AppDashboardTeamRoute
  '/api/cryptomus/webhook': typeof ApiCryptomusWebhookRoute
  '/api/live/session': typeof ApiLiveSessionRoute
  '/api/live/suggest': typeof ApiLiveSuggestRoute
  '/api/live/token': typeof ApiLiveTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/auth/callback'
    | '/workspace/$sessionId'
    | '/workspace/new'
    | '/dashboard/billing'
    | '/dashboard/credits'
    | '/dashboard/interview-prep'
    | '/dashboard/job-descriptions'
    | '/dashboard/live'
    | '/dashboard/mock'
    | '/dashboard/organization'
    | '/dashboard/resume'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/api/cryptomus/webhook'
    | '/api/live/session'
    | '/api/live/suggest'
    | '/api/live/token'
    | '/api/stripe/webhook'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/auth/callback'
    | '/workspace/$sessionId'
    | '/workspace/new'
    | '/dashboard/billing'
    | '/dashboard/credits'
    | '/dashboard/interview-prep'
    | '/dashboard/job-descriptions'
    | '/dashboard/live'
    | '/dashboard/mock'
    | '/dashboard/organization'
    | '/dashboard/resume'
    | '/dashboard/sessions'
    | '/dashboard/settings'
    | '/dashboard/support'
    | '/dashboard/team'
    | '/api/cryptomus/webhook'
    | '/api/live/session'
    | '/api/live/suggest'
    | '/api/live/token'
    | '/api/stripe/webhook'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/auth/callback'
    | '/workspace/$sessionId'
    | '/workspace/new'
    | '/_app/dashboard/billing'
    | '/_app/dashboard/credits'
    | '/_app/dashboard/interview-prep'
    | '/_app/dashboard/job-descriptions'
    | '/_app/dashboard/live'
    | '/_app/dashboard/mock'
    | '/_app/dashboard/organization'
    | '/_app/dashboard/resume'
    | '/_app/dashboard/sessions'
    | '/_app/dashboard/settings'
    | '/_app/dashboard/support'
    | '/_app/dashboard/team'
    | '/api/cryptomus/webhook'
    | '/api/live/session'
    | '/api/live/suggest'
    | '/api/live/token'
    | '/api/stripe/webhook'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  WorkspaceSessionIdRoute: typeof WorkspaceSessionIdRoute
  WorkspaceNewRoute: typeof WorkspaceNewRoute
  ApiCryptomusWebhookRoute: typeof ApiCryptomusWebhookRoute
  ApiLiveSessionRoute: typeof ApiLiveSessionRoute
  ApiLiveSuggestRoute: typeof ApiLiveSuggestRoute
  ApiLiveTokenRoute: typeof ApiLiveTokenRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/new': {
      id: '/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof WorkspaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$sessionId': {
      id: '/workspace/$sessionId'
      path: '/workspace/$sessionId'
      fullPath: '/workspace/$sessionId'
      preLoaderRoute: typeof WorkspaceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/token': {
      id: '/api/live/token'
      path: '/api/live/token'
      fullPath: '/api/live/token'
      preLoaderRoute: typeof ApiLiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/suggest': {
      id: '/api/live/suggest'
      path: '/api/live/suggest'
      fullPath: '/api/live/suggest'
      preLoaderRoute: typeof ApiLiveSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/live/session': {
      id: '/api/live/session'
      path: '/api/live/session'
      fullPath: '/api/live/session'
      preLoaderRoute: typeof ApiLiveSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cryptomus/webhook': {
      id: '/api/cryptomus/webhook'
      path: '/api/cryptomus/webhook'
      fullPath: '/api/cryptomus/webhook'
      preLoaderRoute: typeof ApiCryptomusWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard/team': {
      id: '/_app/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof AppDashboardTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/support': {
      id: '/_app/dashboard/support'
      path: '/dashboard/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof AppDashboardSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/settings': {
      id: '/_app/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/sessions': {
      id: '/_app/dashboard/sessions'
      path: '/dashboard/sessions'
      fullPath: '/dashboard/sessions'
      preLoaderRoute: typeof AppDashboardSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/resume': {
      id: '/_app/dashboard/resume'
      path: '/dashboard/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof AppDashboardResumeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/organization': {
      id: '/_app/dashboard/organization'
      path: '/dashboard/organization'
      fullPath: '/dashboard/organization'
      preLoaderRoute: typeof AppDashboardOrganizationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/mock': {
      id: '/_app/dashboard/mock'
      path: '/dashboard/mock'
      fullPath: '/dashboard/mock'
      preLoaderRoute: typeof AppDashboardMockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/live': {
      id: '/_app/dashboard/live'
      path: '/dashboard/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof AppDashboardLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/job-descriptions': {
      id: '/_app/dashboard/job-descriptions'
      path: '/dashboard/job-descriptions'
      fullPath: '/dashboard/job-descriptions'
      preLoaderRoute: typeof AppDashboardJobDescriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/interview-prep': {
      id: '/_app/dashboard/interview-prep'
      path: '/dashboard/interview-prep'
      fullPath: '/dashboard/interview-prep'
      preLoaderRoute: typeof AppDashboardInterviewPrepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/credits': {
      id: '/_app/dashboard/credits'
      path: '/dashboard/credits'
      fullPath: '/dashboard/credits'
      preLoaderRoute: typeof AppDashboardCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/billing': {
      id: '/_app/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AppDashboardBillingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardBillingRoute: typeof AppDashboardBillingRoute
  AppDashboardCreditsRoute: typeof AppDashboardCreditsRoute
  AppDashboardInterviewPrepRoute: typeof AppDashboardInterviewPrepRoute
  AppDashboardJobDescriptionsRoute: typeof AppDashboardJobDescriptionsRoute
  AppDashboardLiveRoute: typeof AppDashboardLiveRoute
  AppDashboardMockRoute: typeof AppDashboardMockRoute
  AppDashboardOrganizationRoute: typeof AppDashboardOrganizationRoute
  AppDashboardResumeRoute: typeof AppDashboardResumeRoute
  AppDashboardSessionsRoute: typeof AppDashboardSessionsRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardSupportRoute: typeof AppDashboardSupportRoute
  AppDashboardTeamRoute: typeof AppDashboardTeamRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardBillingRoute: AppDashboardBillingRoute,
  AppDashboardCreditsRoute: AppDashboardCreditsRoute,
  AppDashboardInterviewPrepRoute: AppDashboardInterviewPrepRoute,
  AppDashboardJobDescriptionsRoute: AppDashboardJobDescriptionsRoute,
  AppDashboardLiveRoute: AppDashboardLiveRoute,
  AppDashboardMockRoute: AppDashboardMockRoute,
  AppDashboardOrganizationRoute: AppDashboardOrganizationRoute,
  AppDashboardResumeRoute: AppDashboardResumeRoute,
  AppDashboardSessionsRoute: AppDashboardSessionsRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardSupportRoute: AppDashboardSupportRoute,
  AppDashboardTeamRoute: AppDashboardTeamRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  WorkspaceSessionIdRoute: WorkspaceSessionIdRoute,
  WorkspaceNewRoute: WorkspaceNewRoute,
  ApiCryptomusWebhookRoute: ApiCryptomusWebhookRoute,
  ApiLiveSessionRoute: ApiLiveSessionRoute,
  ApiLiveSuggestRoute: ApiLiveSuggestRoute,
  ApiLiveTokenRoute: ApiLiveTokenRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
